#! /usr/bin/env python

import os


os.system('git add -A')
os.system('''git commit -m"up" ''')
try :
    os.system(''' git push ''')
    print ('Already Pushed to CLoud')
except:
    print ('[Warrning]Commited but not pushed to cloud')

